### ISSUE TITLE
main.m: figure, addpath

### ISSUE THREAD

**Issue by Dur0k** [Dur0k/OFDM_TxRx_Chain#21]
**Todo:**
- [ ] addpath of channel etc
- [ ] snr log and ber log plot semilogy
- [ ] more iterations for simulation ca. 5000, more for fsbf x4
