### ISSUE TITLE
Tx: Tx Filter

### ISSUE THREAD

**Issue by Dur0k** [Dur0k/OFDM_TxRx_Chain#6]
`s = filter_tx(z, oversampling_factor, switch_graph, switch_off)`

**Comment by Dur0k** [comment]
**Todo:**
- [ ] use conv and rcosdesign
- [ ] check if coefficients are correct
- [ ] length depending on oversampling_factor not L=20
- [ ] Normalize to 1
